// automatically generated by the FlatBuffers compiler, do not modify

namespace atframe.gw.inner.v1
{

public enum error_code_t : int
{
 EN_ECT_REFUSE_RECONNECT = -1005,
 EN_ECT_SESSION_EXPIRED = -1004,
 EN_ECT_BUSY = -1003,
 EN_ECT_HANDSHAKE = -1002,
 EN_ECT_FIRST_IDEL = -1001,
 EN_ECT_SUCCESS = 0,
};


}
