// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace atframe.gw.inner.v1
{

public enum handshake_step_t : byte
{
 EN_HST_START_REQ = 0,
 EN_HST_START_RSP = 1,
 EN_HST_RECONNECT_REQ = 11,
 EN_HST_RECONNECT_RSP = 12,
 EN_HST_DH_PUBKEY_REQ = 21,
 EN_HST_DH_PUBKEY_RSP = 22,
 EN_HST_ECDH_PUBKEY_REQ = 31,
 EN_HST_ECDH_PUBKEY_RSP = 32,
 EN_HST_RSA_SECRET_REQ = 41,
 EN_HST_RSA_SECRET_RSP = 42,
 EN_HST_VERIFY = 101,
};


}
