// automatically generated by the FlatBuffers compiler, do not modify

namespace atframe.gw.inner.v1
{

public enum handshake_step_t : sbyte
{
 EN_HST_START_REQ = 0,
 EN_HST_START_RSP = 1,
 EN_HST_RECONNECT_REQ = 2,
 EN_HST_RECONNECT_RSP = 3,
 EN_HST_DH_PUBKEY_REQ = 4,
 EN_HST_DH_PUBKEY_RSP = 5,
 EN_HST_RSA_SECRET_REQ = 6,
 EN_HST_RSA_SECRET_RSP = 7,
 EN_HST_VERIFY = 8,
};


}
