// automatically generated by the FlatBuffers compiler, do not modify

namespace atframe.gw.inner.v1
{

public enum switch_secret_t : sbyte
{
 EN_SST_DIRECT = 0,
 EN_SST_DH = 1,
 EN_SST_RSA = 2,
};


}
